name: Test

# This workflow will run on main branch and on any pull requests targeting master
on:
  push:
    branches:
      - main
    tags: []
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: |
          make test-coverage

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
